export const label = {
    // Attribute
    ko: 'Konstitution',
    mu: 'Mut',
    ge: 'Gewandheit',
    kk: 'Körperkraft',
    in: 'Intuition',
    kl: 'Klugheit',
    ch: 'Charisma',
    ff: 'Fingerfertigkeit',
    // Kampfwerte
    ws: 'Wundschwelle',
    ws_stern: 'Effektive Wundschwelle',
    ini: 'Initiative',
    koloss: 'Koloss',
    gs: 'Geschwindigkeit',
    gss: 'Geschwindigkeit (schwimmend)',
    gsf: 'Geschwindigkeit (fliegend)',
    gsr: 'Geschwindigkeit (reitend)',
    schips: 'Schicksalspunkte',
    mr: 'Magieresistenz',
    // Waffeneigenschaften
    kein_malus_nebenwaffe: 'Kein Malus als Nebenwaffe',
    kein_reiter: 'Nicht für Reiter',
    kopflastig: 'Kopflastig',
    niederwerfen: 'Niederwerfen',
    niederwerfen_4: 'Niederwerfen (-4)',
    niederwerfen_8: 'Niederwerfen (-8)',
    parierwaffe: 'Parierwaffe',
    reittier: 'Reittier',
    ruestungsbrechend: 'Rüstungsbrechend',
    schild: 'Schild',
    schwer_4: 'Schwer (4)',
    schwer_8: 'Schwer (8)',
    stationaer: 'Stationär',
    stumpf: 'Stumpf',
    umklammern_212: 'Umklammern (-2,12)',
    umklammern_416: 'Umklammern (-4,16)',
    umklammern_816: 'Umklammern (-8,16)',
    unberechenbar: 'Unberechenbar',
    unzerstoerbar: 'Unzerstörbar',
    wendig: 'Wendig',
    zerbrechlich: 'Zerbrechlich',
    zweihaendig: 'Zweihändig',
    erschoepfung: 'Erschöpfung',
    // Kampfstile
    ohne: 'Kein Stil',
    bhk: 'Beidhändiger Kampf',
    kvk: 'Kraftvoller Kampf',
    pwk: 'Parierwaffenkampf',
    rtk: 'Reiterkampf',
    shk: 'Schildkampf',
    snk: 'Schneller Kampf',
    // Kampfabkürzungen
    kbak: 'Kombinierte Aktion (-4)',
    vldf: 'Volle Defensive (VT +4)',
    vlof: 'Volle Offensive (AT +4, VT -8)',
    vlofok: 'Volle Offensive (AT +4, VT -4)',
    gzkl: 'Größenklasse',
    bwng: 'Bewegung',
    lcht: 'Licht',
    wttr: 'Wetter',
    dckg: 'Deckung',
    kgtl: 'Kampfgetümmel',
    brtn: 'Beritten',
    kwut: 'Kalte Wut',
    // kampfmanoever
    km_ausw: 'Ausweichen (VT -2-BE)',
    km_bind: 'Binden (VT -X)',
    km_ever: 'Entfernung verändern (AT -BE)',
    km_entw: 'Entwaffnen (AT -4 oder VT -4)',
    km_gzsl: 'Gezielter Schlag (AT -2)',
    km_umre: 'Umreißen (AT)',
    km_wusl: 'Wuchtschlag (AT -X, TP +X)',
    km_aufl: 'Auflaufen lassen (VT -4)',
    km_rust: 'Rüstungsbrecher (AT -4)',
    km_shsp: 'Schildspalter (AT +2)',
    km_stsl: 'Stumpfer Schlag (AT)',
    km_umkl: 'Umklammern (AT -X)',
    km_ausf: 'Ausfall (AT -2-BE)',
    km_befr: 'Befreiungsschlag (AT -4)',
    km_dppl: 'Doppelangriff (zwei AT -4)',
    km_hmsl: 'Hammerschlag (AT -8)',
    km_kltz: 'Klingentanz (AT -4)',
    km_ndwf: 'Niederwerfen (AT -4)',
    km_rpst: 'Riposte (VT -4)',
    km_shwl: 'Schildwall (VT -4)',
    km_stag: 'Sturmangriff (Bewegung und AT)',
    km_tdst: 'Todesstoß (AT -8)',
    km_tdst_dm: 'Todesstoß (+2 Wunden)',
    km_uebr: 'Überrennen (Bewegung und AT)',
    km_utlf: 'Unterlaufen (VT -4)',
    fm_gzss: 'Gezielter Schuss (FK -2)',
    fm_rwrh: 'Reichweite erhöhen (FK -4)',
    fm_srfs: 'Scharfschuss (FK -X)',
    fm_zlen: 'Zielen (FK +2)',
    fm_msts: 'Meisterschuss (FK -8)',
    fm_rust: 'Rüstungsbrecher (FK -4)',
    fm_snls: 'Schnellschuss (FK -4)',
    // magiemanöver
    mm_mama: 'Mächtige Magie (-4)',
    mm_mezi: 'Mehrere Ziele (-4)',
    mm_rwrh: 'Reichweite erhöhen (-4)',
    mm_vbvk: 'Vorbereitung verkürzen (-4)',
    mm_wkvl: 'Wirkungsdauer verlängern (-4)',
    mm_ztig: 'Zaubertechnik ignorieren (-4)',
    mm_erzw: 'Erzwingen (+4)',
    mm_kosp: 'Kosten sparen (-4)',
    mm_ztls: 'Zeit lassen (+2)',
    mm_zere: 'Zeremonie (+X)',
    mm_opfe: 'Opferung (+4)',
    // karmamanöver
    lm_mali: 'Mächtige Liturgie (-4)',
    lm_mezi: 'Mehrere Ziele (-4)',
    lm_ltig: 'Liturgische Technik ignorieren (-4)',
    lm_rwrh: 'Reichweite erhöhen (-4)',
    lm_vbvk: 'Vorbereitung verkürzen (-4)',
    lm_wkvl: 'Wirkungsdauer verlängern (-4)',
    lm_kosp: 'Kosten sparen (-4)',
    lm_zere: 'Zeremonie (+X)',
    lm_opfe: 'Opferung (-4)',
    // Inventar
    gewicht: 'Platzbedarf',
    quantity: 'Anzahl',
}
